### ISSUE TITLE
No word wrap on lists

### ISSUE THREAD

**Issue by shompoe** [arturolinares/sn-rme#20]
Hi,

Ordered and unordered list no longer wrap correctly at the end of the line. Instead of wrapping at word breaks, the word at the end of every line is split across 2 lines. I first noticed this happening this morning and it is definitely a new problem. This does not affect normal paragraph text, only lists in markdown. It is affecting both mobile and desktop.

**Comment by shompoe** [comment]
I just installed version 0.11.0 of your extension alongside 0.12.0 and ***on desktop*** this problem is only present with version 0.12.0 of the extension. Unfortunately I'm still getting the problem on mobile, as presumably it just dynamically loads the extension from the latest source code and ignores packaged releases???

**Comment by arturolinares** [comment]
Oh yes, I can see the issue on mobile and desktop. Probably some styles changed on the latest update. I'll try to send a fix later today.

El Wed Nov 25 2020 12:55:12 GMT-0600 (hora estándar central), shompoe escribió:



I just installed version 0.11.0 of your extension alongside 0.12.0 and on desktop this problem is only present with version 0.12.0 of the extension. Unfortunately I'm still getting the problem on mobile, as presumably it just dynamically loads the extension from the latest source code and ignores packaged releases???

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
Enviar con el nuevo e increíble cliente de correo y navegador Vivaldi. Descárgalo en vivaldi.com.
